# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDBjMzkxMDIwNTA0MGVkNmU3YmRmOTRiYjNmY2ZiYmU4ODMzYzI4ZGRlNjMxNmE5Y2E0YTFhM2NiNDkyODY4NTcyNTZmNjQ5NGFmNThlYzkwODc5NzE4MGFjMWU3MDhkMmUxYmI5N2MwMTJlMWRkYjczNTc2Y2E2MDJjMDNkOGE=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: smartComplaint
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: smartComplaint
    password:
